kind: pipeline
name: default

# Limits how many of these builds can run on the drone runner at a time, this isn't about cores
concurrency:
  limit: 1

steps:
  - name: build-release
    image: akkadius/wails:v2.0.3
    environment:
      GH_RELEASE_GITHUB_API_TOKEN:
        from_secret: GH_RELEASE_GITHUB_API_TOKEN
    commands:
      - sudo chown -R go /drone/src
      - sudo chown -R go /home/go/pkg
      - make ci-build
    when:
      branch: [ "main" ]
      event: [ push ]

