// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetExpansionFiles(arg1) {
  return window['go']['main']['App']['GetExpansionFiles'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenFileDialogueEqDir() {
  return window['go']['main']['App']['OpenFileDialogueEqDir']();
}

export function PatchFilesForExpansion(arg1) {
  return window['go']['main']['App']['PatchFilesForExpansion'](arg1);
}
