// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {eqassets} from '../models';

export function DumpPatchFilesForExpansion(arg1:number):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetExpansionFiles(arg1:string):Promise<Array<eqassets.ExpansionFiles>>;

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialogueEqDir():Promise<string>;

export function PatchFilesForExpansion(arg1:number):Promise<void>;
