// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {eqassets} from '../models';

export function GetExpansionFiles(arg1:string):Promise<Array<eqassets.ExpansionFiles>>;

export function Greet(arg1:string):Promise<string>;
