// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInitialization() {
  return window['go']['main']['App']['AppInitialization']();
}

export function AppInitializationCheck() {
  return window['go']['main']['App']['AppInitializationCheck']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function DumpPatchFilesForExpansion(arg1) {
  return window['go']['main']['App']['DumpPatchFilesForExpansion'](arg1);
}

export function GetAssetBasepath() {
  return window['go']['main']['App']['GetAssetBasepath']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEnv() {
  return window['go']['main']['App']['GetEnv']();
}

export function GetExpansionFiles(arg1) {
  return window['go']['main']['App']['GetExpansionFiles'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenFileDialogueEqDir() {
  return window['go']['main']['App']['OpenFileDialogueEqDir']();
}

export function PatchFilesForExpansion(arg1) {
  return window['go']['main']['App']['PatchFilesForExpansion'](arg1);
}
